spring:
  profiles:
    #加载数据配置
    active: druid
  thymeleaf:
    # 关闭模板缓存 false
    cache: false
  #服务模块
  devtools:
    restart:
      # 开启热部署 true
      enabled: true
  #配置时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 设置web服务器
server:
  # 设置端口这里是端口
  port: 8080
  servlet:
    # 设置访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# MyBatis
mybatis-plus:
  configuration:
    #开启Mybatis下划线命名转驼峰命名
    map-underscore-to-camel-case: true
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.llmoe.**.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mybatis/xml/*Mapper.xml
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      select-strategy: not_empty
      #驼峰下划线转换
      db-column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #数据库类型
      db-type: mysql

# 日志配置
logging:
  level:
    com.llmoe.bomb: debug
    org.springframework: warn
    com.baomidou.mybatisplus: DEBUG

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
